version: 2

updates:
  # Keep GitHub Actions up to date
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    labels:
      - "dependencies"
      - "github-actions"
    reviewers:
      - "ridelines/maintainers"
    commit-message:
      prefix: "ci"
      include: "scope"

  # Keep OpenTofu modules up to date
  - package-ecosystem: "terraform"
    directory: "/modules"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "10:00"
    labels:
      - "dependencies"
      - "terraform"
    reviewers:
      - "ridelines/maintainers"
    commit-message:
      prefix: "infrastructure"
      include: "scope"