name: Stage Development Release

on:
  workflow_run:
    workflows: ["Build Deployment Bundle"]
    types: [completed]

permissions:
  contents: write
  packages: read
  id-token: write

jobs:
  call-stage:
    name: Call Base Stage Workflow
    if: github.event.workflow_run.conclusion == 'success'
    uses: ./.github/workflows/base-stage.yml
    with:
      environment: dev
      triggering_job_id: ${{ github.event.workflow_run.id }}
    secrets: inherit