name: Stage Development Release

on:
  workflow_run:
    workflows: ["Build Deployment Bundle"]
    types: [completed]

permissions:
  contents: write
  packages: read
  id-token: write

jobs:
  stage:
    name: Stage Development Release
    if: github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest
    outputs:
      bundle_version: ${{ steps.bundle.outputs.bundle_version }}
    
    steps:
      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get bundle version
        id: bundle
        run: |
          # Extract bundle version from the triggering workflow's display title
          DISPLAY_TITLE="${{ github.event.workflow_run.display_title }}"
          echo "Display title: ${DISPLAY_TITLE}"
          
          # Extract version from "Build bundle - YYYYMMDD-hash" format
          BUNDLE_VERSION=$(echo "${DISPLAY_TITLE}" | sed 's/Build bundle - //')
          echo "bundle_version=${BUNDLE_VERSION}" >> $GITHUB_OUTPUT
          echo "Bundle version: ${BUNDLE_VERSION}"

  call-stage:
    name: Call Base Stage Workflow
    needs: stage
    uses: ./.github/workflows/base-stage.yml
    with:
      environment: dev
      bundle_version: ${{ needs.stage.outputs.bundle_version }}
      trigger_type: new_bundle
    secrets: inherit