name: Stage Development Release

run-name: Stage dev - ${{ github.event.workflow_run.outputs.bundle_version }}

on:
  workflow_run:
    workflows: ["Build Deployment Bundle"]
    types: [completed]

permissions:
  contents: write
  packages: read
  id-token: write

jobs:
  call-stage:
    name: Call Base Stage Workflow
    if: github.event.workflow_run.conclusion == 'success'
    uses: ./.github/workflows/base-stage.yml
    with:
      environment: dev
      bundle_version: ${{ github.event.workflow_run.outputs.bundle_version }}
      trigger_type: new_bundle
    secrets: inherit