name: Deploy to Development

on:
  workflow_run:
    workflows: ["Stage Development Release"]
    types: [completed]

permissions:
  contents: write
  packages: write
  id-token: write

jobs:
  deploy:
    name: Deploy to Development
    if: github.event.workflow_run.conclusion == 'success'
    uses: ./.github/workflows/base-deploy.yml
    with:
      environment: dev
      triggering_job_id: ${{ github.event.workflow_run.id }}
    secrets: inherit