name: Deploy to Development

run-name: Deploy dev - ${{ inputs.bundle_version }}

on:
  workflow_dispatch:
    inputs:
      bundle_version:
        description: 'Bundle version to deploy'
        required: true
        type: string

permissions:
  contents: write
  packages: write
  id-token: write
  actions: write

jobs:
  deploy:
    name: Deploy to Development
    uses: ./.github/workflows/base-deploy.yml
    with:
      environment: dev
      bundle_version: ${{ inputs.bundle_version }}
    secrets: inherit