name: Stage Development Release

on:
  workflow_run:
    workflows: ["Build Deployment Bundle"]
    types: [completed]

permissions:
  contents: write
  packages: read

jobs:
  stage:
    name: Stage Development Release
    if: github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest
    
    steps:
      - name: Get bundle version
        id: bundle
        run: |
          # Get the bundle version from the latest container label
          BUNDLE_VERSION=$(docker inspect ghcr.io/kreed/ridelines-bundle:latest | jq -r '.[0].Config.Labels["ridelines.bundle.version"]')
          echo "bundle_version=${BUNDLE_VERSION}" >> $GITHUB_OUTPUT
          echo "Bundle version: ${BUNDLE_VERSION}"

  call-stage:
    name: Call Base Stage Workflow
    needs: stage
    uses: ./.github/workflows/base-stage.yml
    with:
      environment: dev
      bundle_version: ${{ needs.stage.outputs.bundle_version }}
      trigger_type: new_bundle
    secrets: inherit