name: Deploy to Production

on:
  workflow_run:
    workflows: ["Stage Production Release"]
    types: [completed]

permissions:
  contents: write
  packages: write
  id-token: write

jobs:
  deploy:
    name: Deploy to Production
    if: github.event.workflow_run.conclusion == 'success'
    uses: ./.github/workflows/base-deploy.yml
    with:
      environment: prod
      triggering_job_id: ${{ github.event.workflow_run.id }}
    secrets: inherit