name: Stage Production Release

on:
  release:
    types: [edited]

permissions:
  contents: write
  packages: read

jobs:
  extract-version:
    name: Extract Bundle Version
    # Trigger when a dev release is marked as deployed (changed from prerelease to release)
    if: |
      github.event.release.prerelease == false && 
      startsWith(github.event.release.name, 'dev-') &&
      github.event.changes.prerelease.from == true
    runs-on: ubuntu-latest
    outputs:
      bundle_version: ${{ steps.bundle.outputs.bundle_version }}

    steps:
      - name: Extract bundle version
        id: bundle
        run: |
          # Extract bundle version from release name (format: dev-YYYYMMDD-hash)
          BUNDLE_VERSION=$(echo "${{ github.event.release.name }}" | sed 's/^dev-//')
          echo "bundle_version=${BUNDLE_VERSION}" >> $GITHUB_OUTPUT
          echo "Bundle version: ${BUNDLE_VERSION}"

  stage:
    name: Stage Production Release
    needs: extract-version
    if: needs.extract-version.outputs.bundle_version != ''
    uses: ./.github/workflows/base-stage.yml
    with:
      environment: prod
      bundle_version: ${{ needs.extract-version.outputs.bundle_version }}
      trigger_type: dev_deployed
    secrets: inherit