name: Stage Production Release

run-name: Stage prod - ${{ inputs.bundle_version }}

on:
  workflow_dispatch:
    inputs:
      bundle_version:
        description: 'Bundle version to stage for production'
        required: true
        type: string

permissions:
  contents: write
  packages: read
  id-token: write
  actions: write

jobs:
  stage:
    name: Stage Production Release
    uses: ./.github/workflows/base-stage.yml
    with:
      environment: prod
      bundle_version: ${{ inputs.bundle_version }}
    secrets: inherit