name: Stage Production Release

on:
  workflow_run:
    workflows: ["Deploy to Development"]
    types: [completed]

permissions:
  contents: write
  packages: read
  id-token: write

jobs:
  stage:
    name: Stage Production Release
    if: github.event.workflow_run.conclusion == 'success'
    uses: ./.github/workflows/base-stage.yml
    with:
      environment: prod
      triggering_job_id: ${{ github.event.workflow_run.id }}
    secrets: inherit