name: Deploy to Production

run-name: Deploy prod - ${{ inputs.bundle_version }}

on:
  workflow_dispatch:
    inputs:
      bundle_version:
        description: 'Bundle version to deploy'
        required: true
        type: string

permissions:
  contents: write
  packages: write
  id-token: write

jobs:
  deploy:
    name: Deploy to Production
    uses: ./.github/workflows/base-deploy.yml
    with:
      environment: prod
      bundle_version: ${{ inputs.bundle_version }}
    secrets: inherit