name: Deploy to Production

on:
  release:
    types: [published]

permissions:
  contents: write
  packages: write
  id-token: write

jobs:
  deploy:
    name: Deploy to Production
    # Only trigger for prod staging releases (prereleases starting with "prod-")
    if: github.event.release.prerelease == true && startsWith(github.event.release.name, 'prod-')
    uses: ./.github/workflows/shared/base-deploy.yml
    with:
      environment: prod
      release_name: ${{ github.event.release.name }}
    secrets: inherit